"""
Tests for the full-namespace GO search index and the directional-label correction.

Background: /search_go_terms resolved against the same gene-count-filtered metadata
as the Suggested list, so any term outside [MIN_GENES, MAX_GENES] was unreachable
through the GUI by *any* route — neither suggested nor searchable, not even by
pasting its exact GO ID. Screening one 196-term curated KE->GO set against
production found 62 such terms (32%), among them "peroxisome proliferator activated
receptor signaling pathway", "hepatocyte proliferation" and "DNA repair".

The fix decouples the two: search resolves against a full-namespace index while the
BioBERT-ranked suggestion corpus keeps its filter. Search needs no embeddings, so
this costs one JSON artifact and no re-embed.
"""
import pytest

from src.suggestions.go import GoSuggestionService
from src.utils.text import is_directional_go_label


# The gene-count-filtered suggestion corpus: what Suggested ranks over.
SUGGESTION_CORPUS = {
    "GO:0006915": {"name": "apoptotic process", "definition": "A programmed cell death process."},
}

# The full namespace: everything a curator may legitimately search for. Includes
# terms the gene-count filter drops from both tails.
FULL_INDEX = {
    "GO:0006915": {"name": "apoptotic process", "definition": "A programmed cell death process."},
    # <10 propagated genes — dropped by MIN_GENES
    "GO:0035357": {
        "name": "peroxisome proliferator activated receptor signaling pathway",
        "definition": "A series of molecular signals generated by a PPAR binding its ligand.",
    },
    "GO:0072574": {"name": "hepatocyte proliferation", "definition": "The multiplication of hepatocytes."},
    # >500 propagated genes — dropped by MAX_GENES
    "GO:0006281": {"name": "DNA repair", "definition": "The process of restoring damaged DNA."},
    # no human gene annotation at all — unreachable by ANY MIN/MAX setting
    "GO:0032640": {"name": "tumor necrosis factor production", "definition": "The appearance of TNF."},
}


def _service(search_index=None, corpus=None):
    """A GoSuggestionService without running __init__ (loads no corpus files)."""
    svc = object.__new__(GoSuggestionService)
    svc.go_metadata = SUGGESTION_CORPUS if corpus is None else corpus
    svc.go_search_metadata = {} if search_index is None else search_index
    svc.go_mf_metadata = {}
    svc.go_gene_annotations = {}
    svc.go_mf_gene_annotations = {}
    return svc


# ---------------------------------------------------------------------------
# bp_search_index — the fallback contract
# ---------------------------------------------------------------------------

def test_search_index_used_when_loaded():
    svc = _service(search_index=FULL_INDEX)
    assert svc.bp_search_index is FULL_INDEX


def test_falls_back_to_suggestion_corpus_when_index_absent():
    """An older data mount, or a dev checkout with no corpus, must still search."""
    svc = _service(search_index={})
    assert svc.bp_search_index is SUGGESTION_CORPUS


def test_falls_back_when_attribute_missing_entirely():
    """Instances built without __init__ must not raise AttributeError."""
    svc = object.__new__(GoSuggestionService)
    svc.go_metadata = SUGGESTION_CORPUS
    assert svc.bp_search_index is SUGGESTION_CORPUS


# ---------------------------------------------------------------------------
# The regression this whole change exists to prevent
# ---------------------------------------------------------------------------

@pytest.mark.parametrize(
    "go_id",
    ["GO:0035357", "GO:0072574", "GO:0006281", "GO:0032640"],
)
def test_exact_go_id_resolves_for_terms_outside_the_suggestion_corpus(go_id):
    """Pasting a GO ID must resolve any valid BP term, not just corpus members."""
    svc = _service(search_index=FULL_INDEX)
    results = svc.search_go_terms(go_id)
    assert [r["go_id"] for r in results] == [go_id]
    assert results[0]["relevance_score"] == 1.0


def test_exact_go_id_out_of_corpus_returns_nothing_without_the_index():
    """Documents the old, broken behaviour so a regression is unmistakable."""
    svc = _service(search_index={})
    assert svc.search_go_terms("GO:0035357") == []


def test_fuzzy_search_reaches_terms_outside_the_suggestion_corpus():
    svc = _service(search_index=FULL_INDEX)
    hits = {r["go_id"] for r in svc.search_go_terms("hepatocyte proliferation", threshold=0.2)}
    assert "GO:0072574" in hits


def test_go_id_forms_are_normalised():
    svc = _service(search_index=FULL_INDEX)
    for query in ("GO:0006281", "go:0006281", "GO_0006281", "GO-0006281", "GO:6281"):
        assert [r["go_id"] for r in svc.search_go_terms(query)] == ["GO:0006281"], query


def test_unknown_go_id_still_returns_empty():
    svc = _service(search_index=FULL_INDEX)
    assert svc.search_go_terms("GO:9999999") == []


# ---------------------------------------------------------------------------
# Suggested must NOT inherit the widened index
# ---------------------------------------------------------------------------

def test_widening_search_does_not_widen_the_suggestion_corpus():
    """go_metadata drives ranking and is enumerated as "the candidate set"; if the
    full index leaked into it, ~24k unranked terms would surface as suggestions."""
    svc = _service(search_index=FULL_INDEX)
    assert svc.go_metadata == SUGGESTION_CORPUS
    assert "GO:0035357" not in svc.go_metadata


# ---------------------------------------------------------------------------
# Directional-label correction
# ---------------------------------------------------------------------------

# Measured over all 24,129 BP labels: r"\bactivated\b" matched 88 terms and not one
# encoded a direction. r"\binhibited\b" matched none.
NOT_DIRECTIONAL_PAST_PARTICIPLE = [
    "peroxisome proliferator activated receptor signaling pathway",
    "angiotensin-activated signaling pathway",
    "TRAIL-activated apoptotic signaling pathway",
    "VEGF-activated neuropilin signaling pathway",
    "CXCL12-activated CXCR4 signaling pathway",
    "abscisic acid-activated signaling pathway",
    "activated T cell proliferation",
    "activated CD4-positive, alpha-beta T cell apoptotic process",
    "calcium activated phospholipid scrambling",
]


@pytest.mark.parametrize("name", NOT_DIRECTIONAL_PAST_PARTICIPLE)
def test_past_participle_qualifiers_are_not_directional(name):
    """"X-activated Y" names a ligand or a cell state, it does not sign the term."""
    assert is_directional_go_label(name) is False


@pytest.mark.parametrize(
    "name",
    [
        "positive regulation of activated T cell proliferation",
        "negative regulation of peroxisome proliferator activated receptor signaling pathway",
        "positive regulation of apoptotic process",
        "activation of protein kinase activity",
    ],
)
def test_genuinely_signed_labels_are_still_directional(name):
    """The regulation patterns already catch the signed variants of the above."""
    assert is_directional_go_label(name) is True


def test_ligand_activated_pathways_survive_fuzzy_search():
    """The runtime guard also filters search results, so the corrected regex is
    what actually lets these terms reach a curator."""
    index = {
        "GO:0038166": {
            "name": "angiotensin-activated signaling pathway",
            "definition": "A series of molecular signals initiated by angiotensin.",
        },
        "GO:0001234": {
            "name": "positive regulation of angiotensin-activated signaling pathway",
            "definition": "Any process that increases the above.",
        },
    }
    svc = _service(search_index=index)
    hits = {r["go_id"] for r in svc.search_go_terms("angiotensin-activated signaling pathway", threshold=0.2)}
    assert "GO:0038166" in hits
    assert "GO:0001234" not in hits, "the signed variant must still be excluded"


# ---------------------------------------------------------------------------
# Corpus build: definitions are parsed, and the search index spans the namespace
# ---------------------------------------------------------------------------

MINI_OBO = """format-version: 1.2

[Term]
id: GO:0035357
name: peroxisome proliferator activated receptor signaling pathway
namespace: biological_process
def: "A series of molecular signals generated by a PPAR binding its ligand." [GOC:signaling]
is_a: GO:0030522 ! intracellular receptor signaling pathway

[Term]
id: GO:0006281
name: DNA repair
namespace: biological_process
def: "The process of restoring damaged DNA, involving \\"excision\\" steps." [GOC:go_curators]
is_a: GO:0006259 ! DNA metabolic process

[Term]
id: GO:0000003
name: obsolete thing
namespace: biological_process
def: "Do not use." [GOC:x]
is_obsolete: true

[Term]
id: GO:0003674
name: molecular_function
namespace: molecular_function
def: "A molecular process." [GOC:x]
"""


def test_obo_parser_extracts_definitions(tmp_path):
    """Search fuzzy-matches on definitions, so the corpus build must carry them."""
    from scripts import precompute_go_hierarchy as pgh

    obo = tmp_path / "mini.obo"
    obo.write_text(MINI_OBO, encoding="utf-8")
    terms, _ = pgh.parse_obo_file(str(obo), namespace_value="biological_process")

    assert set(terms) == {"GO:0035357", "GO:0006281"}, "obsolete and MF terms excluded"
    assert terms["GO:0035357"]["definition"].startswith("A series of molecular signals")
    # The trailing [xref] list is not searchable text and must be stripped, while
    # quotes inside the definition body are preserved.
    assert "[GOC:" not in terms["GO:0006281"]["definition"]
    assert terms["GO:0006281"]["definition"].endswith('steps.') or \
        'excision' in terms["GO:0006281"]["definition"]


def test_parsed_terms_feed_a_full_namespace_search_index(tmp_path):
    """The index the app searches is built straight off the parsed terms, so a
    gene-count-filtered term is still present in it."""
    from scripts import precompute_go_hierarchy as pgh

    obo = tmp_path / "mini.obo"
    obo.write_text(MINI_OBO, encoding="utf-8")
    terms, _ = pgh.parse_obo_file(str(obo), namespace_value="biological_process")

    search_index = {
        go_id: {"name": data["name"], "definition": data.get("definition") or ""}
        for go_id, data in terms.items()
    }
    svc = _service(search_index=search_index)
    assert [r["go_id"] for r in svc.search_go_terms("GO:0035357")] == ["GO:0035357"]
    assert [r["go_id"] for r in svc.search_go_terms("GO:0006281")] == ["GO:0006281"]
